workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter pub get
      
      - name: Build Debug APK
        script: | 
          flutter build apk --debug
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - alinatripura22@gmail.com
        notify:
          success: true
          failure: true
