workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.vibbeo.app"
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: Build APK
        script: |
          flutter build apk --release
    
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
